version: '3.9'

services:
  web-client:
    build: ./web-client
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production

  vote-api:
    build: ./vote-api
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production

  docs:
    build: ./docs
    ports:
      - "80:80"
  
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vote
    ports:
      - "5432:5432"